version: "3"

services:
  db:
    image: postgres:10
    container_name: "pg_db"
    ports:
      - 5432:5432
    expose:
      - "5432"
    restart: always
    env_file:
      - postgres.env
    volumes:
      - ./dockerSetup/postgres/:/var/liv/postgersql/data
    logging:
      driver: "json-file"
      options:
        max-size: "25m"
  backend:
    build: ./packages/backend
    depends_on:
      - db
    ports:
      - 1234:8080
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db

    ports:
      - 8081:8080
